name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: 23bc12d6bd4ee799c3b1c79790b12f6a
          command: pages deploy . --project-name=jd-hx
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CF_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CF_EMAIL }}
